# Dzięki plikom `.http` możesz testować endpointy HTTP bezpośrednio z edytora kodu.
# W uruchomieniu tych plików pomoże Ci rozszerzenie "REST Client" w Visual Studio Code.

### Sprawdzanie działania endpointu /data
GET http://localhost:3035/guests

### Sprawdzanie działania dla jednego gościa
GET http://localhost:3035/guests/1

### Sprawdzanie działania dla jednego gościa
POST http://localhost:3035/guests
Content-Type: application/json

{
    "name": "Mój gość"
}


### Sprawdzanie działania nieistniejącego endpointu
GET http://localhost:3035/datazz