### Get all guests

GET http://localhost:{{$dotenv PORT}}/guests
#Authorization: Barer xyz712537561


### Get all guests invited
GET http://localhost:{{$dotenv PORT}}/guests?status=invited

### Get all guests confirmed
GET http://localhost:{{$dotenv PORT}}/guests?status=confirmed

### Get single guest by uuid

GET http://localhost:{{$dotenv PORT}}/guests/123e4567-e89b-12d3-a456-426614174000

### Get single guest uuid(123e4567-e89b-12d3-a456-426614174001)

GET http://localhost:{{$dotenv PORT}}/guests/123e4567-e89b-12d3-a456-426614174001

### Get single - handle 404 Error

GET http://localhost:{{$dotenv PORT}}/guests/222

### Add one Guest

POST http://localhost:{{$dotenv PORT}}/guests
Content-Type: application/json

{
   "name": "Jan",
   "lastName": "Kowalski"
}